apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-pvc
  labels:
    app: elasticsearch
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/elasticsearch