apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-configmap
  labels:
    app: elasticsearch
data:
  ELASTIC_PASSWORD: "SomeElasticPass1"
  discovery.type: single-node
  xpack.security.enabled: 'false'