apiVersion: v1
kind: PersistentVolume
metadata:
  name: hangfire-pv
  labels:
    app: hangfire
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/hangfire