apiVersion: v1
kind: ConfigMap
metadata:
  name: communications-config
  labels:
    app: communications
data:
  ConnectionStrings__DatabaseConnection: "Server=communications-db,9824;database=communications;user id=SA;password=CommunicationsDbServerPass17"
  ConnectionStrings__KafkaBootstrapServers: "kafka:29092"
  ConnectionStrings__HangfireStorage: "Server=hangfire-db,9825;database=hangfire;user id=SA;password=HangfireDbServerPass17"
  ConnectionStrings__ElasticSearchNode: "http://elastic-search-node:9200"
  ASPNETCORE_URLS: http://0.0.0.0:9999/
  ElasticSearch__ReportsIndexName: "reports"
  ElasticSearch__NotificationsIndexName: "notifications"
  ElasticSearch__QueriedElementsAmount: "10"