apiVersion: v1
kind: PersistentVolume
metadata:
  name: civilians-db-pv
  labels:
    app: civilians-db
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/civilians