apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authorities-db-pvc
  labels:
    app: authorities-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi