apiVersion: v1
kind: PersistentVolume
metadata:
  name: authorities-db-pv
  labels:
    app: authorities-db
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/authorities