apiVersion: v1
kind: ConfigMap
metadata:
  name: communications-configmap
  labels:
    app: communications
data:
  ASPNETCORE_URLS: http://0.0.0.0:9000/
  Authentication__Jwt__civilians__Key: "x1ACHGEzgl2AdREsEzePUQiTndFlUQpbCbFdq98PWkmdNWAiMioYIFK3y15PaSMr"
  Authentication__Jwt__civilians__Issuer: "civilians-acc-msvc-iss"
  Authentication__Jwt__civilians__Audience: "civilians-acc-msvc-usr"
  Authentication__Jwt__authorities__Key: "dq98PWkmdNWAiMioYIFK3y15PaSMrx1ACHGEzgl2AdREsEzePUQiTndFlUQpbCbF"
  Authentication__Jwt__authorities__Issuer: "authorities-acc-msvc-iss"
  Authentication__Jwt__authorities__Audience: "authorities-acc-msvc-usr"