version: "3.9"
services:    

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    networks:
      - gov-connect-net

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    networks:
      - gov-connect-net
    depends_on:
      - zookeeper
      
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    networks:
      - gov-connect-net
    depends_on:
      - kafka

  authorities-db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    networks:
      - gov-connect-net   
  
  authorities-accounts:
    build:
      context: .
      dockerfile: AuthoritiesAccountsMicroservice/Dockerfile
    networks:
      - gov-connect-net
    depends_on:
      - authorities-db

  civilians-db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    networks:
      - gov-connect-net    
      
  civilians-accounts:
    build:
      context: .
      dockerfile: CiviliansAccountsMicroservice/Dockerfile 
    networks:
      - gov-connect-net
    depends_on:
      - civilians-db
      - kafka
      
  hangfire-db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    networks:
      - gov-connect-net
  
  communications-db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    networks:
      - gov-connect-net
  
  communications:
    build:
      context: .
      dockerfile: CommunicationsMicroservice/Dockerfile
    networks:
      - gov-connect-net
    depends_on:
      - communications-db
      - kafka
      - hangfire-db
      
  gateway:
    build:
      context: .
      dockerfile: Gateway/Dockerfile
    networks:
      - gov-connect-net
    depends_on:
      - authorities-accounts
      - civilians-accounts
      - communications
      
networks:
  gov-connect-net:
    driver: bridge