version: "3.9"
services:    

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    networks:
      - gov-connect-net

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    networks:
      - gov-connect-net
    depends_on:
      - zookeeper
      
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    networks:
      - gov-connect-net
    depends_on:
      - kafka

  redis:
    image: redis
    networks:
      - gov-connect-net

  authorities-db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    networks:
      - gov-connect-net   
  
  authorities-accounts:
    image: authorities-img
    build:
      context: .
      dockerfile: AuthoritiesAccountsMicroservice/Dockerfile
    networks:
      - gov-connect-net
    depends_on:
      - authorities-db

  civilians-db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    networks:
      - gov-connect-net    
      
  civilians-accounts:
    image: civilians-img
    build:
      context: .
      dockerfile: CiviliansAccountsMicroservice/Dockerfile 
    networks:
      - gov-connect-net
    depends_on:
      - civilians-db
      - kafka
      
  hangfire-db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    networks:
      - gov-connect-net
      
  elastic-search-node:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1 
    networks:
      - gov-connect-net
      
  kibana:
    image: kibana:8.7.1
    networks:
      - gov-connect-net
    depends_on:
      - elastic-search-node
  
  communications-db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    networks:
      - gov-connect-net
  
  communications:
    image: communications-img
    build:
      context: .
      dockerfile: CommunicationsMicroservice/Dockerfile
    networks:
      - gov-connect-net
    depends_on:
      - communications-db
      - kafka
      - hangfire-db
      - elastic-search-node
      - redis
      
  gateway:
    image: gateway-img
    build:
      context: .
      dockerfile: Gateway/Dockerfile
    networks:
      - gov-connect-net
    depends_on:
      - authorities-accounts
      - civilians-accounts
      - communications
      
networks:
  gov-connect-net:
    driver: bridge