version: "3.9"
services:    

  zookeeper:
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    ports:
      - "9001:9001"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9001
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_CLEANER_DELETE_RETENTION_MS: 5000
      KAFKA_BROKER_ID: 1
      KAFKA_MIN_INSYNC_REPLICAS: 1
      
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: communications
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092

  authorities-db:
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "AuthoritiesAccountsDbServerPass17"
      MSSQL_PID: "Express"
      MSSQL_TCP_PORT: "9823"
  
  authorities-accounts:
    ports:
      - "9997:9997"
    environment:
      ConnectionStrings__DatabaseConnection: "Server=authorities-db,9823;database=authorities-accounts;user id=SA;password=AuthoritiesAccountsDbServerPass17"
      ASPNETCORE_URLS: http://0.0.0.0:9997/    
      Authentication__Jwt__Key: "dq98PWkmdNWAiMioYIFK3y15PaSMrx1ACHGEzgl2AdREsEzePUQiTndFlUQpbCbF"
      Authentication__Jwt__Issuer: "authorities-acc-msvc-iss"
      Authentication__Jwt__Audience: "authorities-acc-msvc-usr"
      Authentication__Jwt__AuthTokenLifetimeInMinutes: 10
      Authentication__Jwt__RefreshTokenLifetimeInDays: 1
      Authentication__Jwt__SecurityAlgorithm: "HS256"
      
  civilians-db:
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "CiviliansAccountsDbServerPass17"
      MSSQL_PID: "Express"
      MSSQL_TCP_PORT: "9824"     
      
  civilians-accounts:
    ports:
      - "9998:9998"
    environment:
      ConnectionStrings__DatabaseConnection: "Server=civilians-db,9824;database=civilians-accounts;user id=SA;password=CiviliansAccountsDbServerPass17"
      ConnectionStrings__KafkaBootstrapServers: "kafka:29092"
      ASPNETCORE_URLS: http://0.0.0.0:9998/    
      Authentication__Jwt__Key: "x1ACHGEzgl2AdREsEzePUQiTndFlUQpbCbFdq98PWkmdNWAiMioYIFK3y15PaSMr"
      Authentication__Jwt__Issuer: "civilians-acc-msvc-iss"
      Authentication__Jwt__Audience: "civilians-acc-msvc-usr"
      Authentication__Jwt__AuthTokenLifetimeInMinutes: 30
      Authentication__Jwt__RefreshTokenLifetimeInDays: 7
      Authentication__Jwt__SecurityAlgorithm: "HS256"

  hangfire-db:
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "HangfireDbServerPass17"
      MSSQL_PID: "Express"
      MSSQL_TCP_PORT: "9825" 
      
  elastic-search-node:
    ports:
      - "9200:9200"
    environment:
      ELASTIC_PASSWORD: "SomeElasticPass1"
      discovery.type: single-node
      xpack.security.enabled: 'false'
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
      
  kibana:
    ports:
      - "5601:5601"

  communications-db:
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "CommunicationsDbServerPass17"
      MSSQL_PID: "Express"
      MSSQL_TCP_PORT: "9826"  
  
  communications:
    ports:
      - "9999:9999"
    environment:
      ConnectionStrings__DatabaseConnection: "Server=communications-db,9826;database=communications;user id=SA;password=CommunicationsDbServerPass17"
      ConnectionStrings__KafkaBootstrapServers: "kafka:29092"
      ConnectionStrings__HangfireStorage: "Server=hangfire-db,9825;database=hangfire;user id=SA;password=HangfireDbServerPass17"
      ConnectionStrings__ElasticSearchNode: "http://elastic-search-node:9200"
      ASPNETCORE_URLS: http://0.0.0.0:9999/
      ElasticSearch__ReportsIndexName: "reports"
      ElasticSearch__NotificationsIndexName: "notifications"
      ElasticSearch__QueriedElementsAmount: 10      
      
  gateway:
    ports:
      - "9000:9000"
    environment:
      ASPNETCORE_URLS: http://0.0.0.0:9000/
      Authentication__Jwt__civilians__Key: "x1ACHGEzgl2AdREsEzePUQiTndFlUQpbCbFdq98PWkmdNWAiMioYIFK3y15PaSMr"
      Authentication__Jwt__civilians__Issuer: "civilians-acc-msvc-iss"
      Authentication__Jwt__civilians__Audience: "civilians-acc-msvc-usr"
      Authentication__Jwt__authorities__Key: "dq98PWkmdNWAiMioYIFK3y15PaSMrx1ACHGEzgl2AdREsEzePUQiTndFlUQpbCbF"
      Authentication__Jwt__authorities__Issuer: "authorities-acc-msvc-iss"
      Authentication__Jwt__authorities__Audience: "authorities-acc-msvc-usr"