apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: communications-db-pvc
  labels:
    app: communications-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi