apiVersion: v1
kind: PersistentVolume
metadata:
  name: communications-db-pv
  labels:
    app: communications-db
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/communications