name: (Authorities) Build and Deploy to GKE

on:
  push:
    branches: 
      - main

env:
  IMAGE_NAME: authorities-img
  SERVICE_NAME: authorities
  PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
  CLUSTER_NAME: ${{ vars.GKE_CLUSTER_NAME }}
  CLUSTER_LOCATION: ${{ vars.GKE_CLUSTER_LOCATION }}
  REGISTRY_NAME: ${{ vars.GAR_NAME }}
  REGISTRY_LOCATION: ${{ vars.GAR_LOCATION }}

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Configure Workload Identity Federation and generate an access token.
    - id: auth
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: ${{ secrets.JSON_KEY }}
        token_format: 'access_token'

    - name: Docker configuration
      run: |-
        echo ${{steps.auth.outputs.access_token}} | docker login -u oauth2accesstoken --password-stdin https://$GAR_LOCATION-docker.pkg.dev
    # Get the GKE credentials so we can deploy to the cluster
    - name: Set up GKE credentials
      uses: google-github-actions/get-gke-credentials@v0
      with:
        cluster_name: $CLUSTER_NAME
        location: $CLUSTER_LOCATION

    # Build the Docker image
    - name: Build
      run: |-
        docker build \
          --file folder/Dockerfile \
          --tag "$REGISTRY_LOCATION-docker.pkg.dev/$PROJECT_ID/$REGISTRY_NAME/$IMAGE_NAME:${{ github.sha }}" \
          .

    # Push the Docker image to Google Artifact Registry
    - name: Publish
      run: |-
        docker push "$REGISTRY_LOCATION-docker.pkg.dev/$PROJECT_ID/$REGISTRY_NAME/$IMAGE_NAME:${{ github.sha }}"
    # Set up kustomize
    - name: Set up Kustomize
      run: |-
        curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
        chmod u+x ./kustomize
    
    - name: Change image name in Kustomize
      run: |-
          sed -i "s|image:.*|image: $REGISTRY_LOCATION-docker.pkg.dev/$PROJECT_ID/$REGISTRY_NAME/$IMAGE_NAME:${{ github.sha }}|g" ./Kubernetes/main-service/main-service-deployment.yaml
    
    # Deploy the Docker image to the GKE cluster
    - name: Deploy
      run: |-
        sed -i "s|image:.*|image: $REGISTRY_LOCATION-docker.pkg.dev/$PROJECT_ID/$REGISTRY_NAME/$IMAGE_NAME:${{ github.sha }}|g" \ 
        ./src/Kubernetes/$SERVICE_NAME/$SERVICE_NAME-deployment.yaml
        ./kustomize edit set image LOCATION-docker.pkg.dev/PROJECT_ID/REGISTRY_NAME/IMAGE:TAG=$REGISTRY_LOCATION-docker.pkg.dev/$PROJECT_ID/$REGISTRY_NAME/$IMAGE_NAME:${{ github.sha }}
        ./kustomize build .\src\Kubernetes | kubectl apply -f -
        kubectl rollout status deployment/$SERVICE_NAME
        kubectl get services -o wide