name: CI/CD Gateway

on:
  workflow_call:

jobs:
  CI:
    uses: the-17th-fox/GovConnect/.github/workflows/ci-workflow.yaml@main
  CD:
    needs: CI
    uses: the-17th-fox/GovConnect/.github/workflows/base-cd-workflow.yaml@main
    with:
      IMAGE_NAME: "gateway-img"
      SERVICE_NAME: "gateway"